### ISSUE TITLE
listenerCount is on EE.prototype as of node v4

### ISSUE THREAD

**Issue by jasonkarns** [Gozala/events#19]
EventEmitter.listenerCount is now (node v4) deprecated in favor of EventEmitter.prototype.listenerCount

https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4#events

https://github.com/nodejs/node/commit/8f58fb92fff904a6ca58fd0df9ee5a1816e5b84e

**Comment by jscissr** [comment]
+1 I too need this for updating [http-node](https://github.com/jscissr/http-node).

While `listenerCount` seems to be the only API change, there are also a lot of internal changes, like performance optimizations.

I would have simply made a pull request, however it looks like this repo is not an exact copy of Node but has custom changes. You (maintainers of this repo) probably know best what to do.

**Comment by dcousens** [comment]
I added it [here](https://github.com/Gozala/events/issues/19),  @Gozala please merge when possible :)

**Comment by dcousens** [comment]
ping @defunctzombie

**Comment by jasonkarns** [comment]
shouldn't the static variant be implemented in terms of the instance
variant instead of the other way around? Since the static variant is now
deprecated and will be removed eventually?

**Comment by dcousens** [comment]
@jasonkarns yes,  it should.  But this solves the issue immediately for those of us using this in production.

**Comment by defunctzombie** [comment]
fixed in v1.1.0
