### ISSUE TITLE
A better way to unset events?

### ISSUE THREAD

**Issue by jamen** [Gozala/events#27]
I know there are methods to remove events, such as  `removeListener` and `removeAllListeners`.  But I think there should be a better method of removing events that don't correlate to the listener itself.  Perhaps `.on` could return an object that keeps chainability, but also has special methods to kill that singular event.

```javascript
let bar = foo.on(...);
bar.unset();
foo.on(...).on(...)
```

**Comment by defunctzombie** [comment]
Won't implement. This module is mostly for parity with nodejs events module and won't be implementing handler baton like features as described. I too think such a feature would be nice but it would mean breaking parity with nodejs event emitter module
