### ISSUE TITLE
Wish: document in what cases this is needed

### ISSUE THREAD

**Issue by markstos** [Gozala/events#28]
Node.js have a native `events` implementation, so it would be useful to note in the README in what cases there is a benefit or requirement to use this module over the native `events` module.

**Comment by amir-arad** [comment]
used by browserify to simulate node.js environment in the browser

**Comment by markstos** [comment]
@defunctzombie Why close this? Is better documentation deemed unnecessary or undesirable?

**Comment by defunctzombie** [comment]
PR would be welcome but there is no real requirement to use this module. You can use it in node or browser if you want to have a particular version of events module. Hard for me to say explicitly what the benefit is for your cases.
